---
name: WWW-Shorten-urlTea
version: 0.02
author:
  - Brandon Gilmore <brandon@mg2.org>
abstract: Perl interface to urlTea.com
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  WWW::Shorten: 1.97
build_requires:
  Test::More: 0
provides:
  WWW::Shorten::urlTea:
    file: lib/WWW/Shorten/urlTea.pm
    version: 0.02
generated_by: vim
